name: 🚀 功能请求 | Feature Request
description: 请详细描述您期望的功能。 | Please describe in detail the features you expect.
title: "【功能请求】: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        我有一个好的功能建议想向你提供。
  - type: textarea
    id: what-happened
    attributes:
      label: 功能描述
      description: 您使用的场景?您期望的结果是怎样的？
      placeholder: 请输入描述!
      value: "1.\n2.\n3"
    validations:
      required: true

